name: Run Typescript Checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    secrets:
      AIRTABLE_TOKEN:
        required: true

jobs:
  typescript-check:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_PEOPLE_BASE_ID: appk2btw36qEO3vFo
      AIRTABLE_RESEARCH_BASE_ID: appTv9J1zxqaNgBHi
      AIRTABLE_EVENTS_BASE_ID: tbl6CURONRn8ML6le
      AIRTABLE_POSTS_BASE_ID: appsY0VXF7pbv3mKR
      AIRTABLE_MITH_BASE_ID: appMWsw8HKjjokBg2

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Check for gatsby-types.d.ts
        run: |
          ls -l src/gatsby-types.d.ts
          cat src/gatsby-types.d.ts | head -n 20
      - name: Run TypeScript check
        run: npm run check
