name: Publish Staging Site on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_API_KEY  }}
          AIRTABLE_PEOPLE_BASE_ID: appk2btw36qEO3vFo
          AIRTABLE_RESEARCH_BASE_ID: appTv9J1zxqaNgBHi
          AIRTABLE_EVENTS_BASE_ID: tbl6CURONRn8ML6le
          AIRTABLE_POSTS_BASE_ID: appsY0VXF7pbv3mKR
          AIRTABLE_MITH_BASE_ID: appMWsw8HKjjokBg2
        with:
          node-version: 20.x
      - name: npm install and build and deploy
        run: |
          npm install
          npm run build
      - uses: peaceiris/actions-gh-pages@v4
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public